### ISSUE TITLE
Art is garbage lmao

### ISSUE THREAD

**Issue by quat1024** [quat1024/modjam_what#1]
seriously the breadcrumb looks like a turd both inside of the inventory and out

also lol this 1 bit bag texture

**Comment by towerofnix** [comment]
![breadcrumb](https://user-images.githubusercontent.com/9948030/38197439-78d1835e-365e-11e8-82a2-59f54849c696.png)

![breadcrumb2](https://user-images.githubusercontent.com/9948030/38197459-8d8b6e7c-365e-11e8-9416-3c3d4e1a043b.png)

**Comment by Spazmunki13** [comment]
I'm no sprite artist but felt like offering up a little help:

![breadcrumbpouch](https://user-images.githubusercontent.com/29984387/38227776-e622654e-36cd-11e8-90f7-34ece888d8f9.png)

![photoshop_2018-04-02_23-30-00](https://user-images.githubusercontent.com/29984387/38227783-ee696612-36cd-11e8-9e0c-de8e6355a5be.png)

**Comment by quat1024** [comment]
both of you are awesome, thanks so much :package:

**Comment by quat1024** [comment]
@towerofnix what do you think of this modification?
![image](https://user-images.githubusercontent.com/2068021/38345305-6573c038-385c-11e8-8d61-974a1eaa9de0.png)
trying to cut down on the "teardrop" shape/perfect 45 degree angles

**Comment by quat1024** [comment]
also, @Spazmunki13 aAAAAa i can't get over how awesome this bag texture is. love ya. I want to use this SO BAD

I've been trying to draw an "open" version of it so I can use it in the mod and it's uh, not going so well
![image](https://user-images.githubusercontent.com/2068021/38346173-5f5ba094-3861-11e8-8fce-68b7d4d98160.png)

**Comment by towerofnix** [comment]
@quat1024 re: breadcrumb, looks good to me!! :tada:

(Also the open bag looks very nice too)

**Comment by Spazmunki13** [comment]
@quat1024 Oh! I see what you're going for.

I was thinking the pouch had a hole it in (like Hansel and Gretel?) hence the dark spot in the bottom right.

I'll see if I can whip you up a pair of textures that work for what you need later today.

**Comment by Spazmunki13** [comment]
Sorry for the delay.
![breadcrumbpouch](https://user-images.githubusercontent.com/29984387/38459923-3cf763a2-3a7e-11e8-8a80-491891ec9ebe.png)
![breadcrumbpouchopen](https://user-images.githubusercontent.com/29984387/38459924-3d03eaaa-3a7e-11e8-91f8-f1e298eca857.png)

![photoshop_2018-04-07_16-10-25](https://user-images.githubusercontent.com/29984387/38459929-4abfeaa4-3a7e-11e8-814b-16b964cddd16.png)

Hope this works for you. :)

EDIT: Realized the colour was off on that pair. Here's the two in the original colour. (I think this colour fits better with the leather texture, but that's just me.)

![breadcrumbpouch](https://user-images.githubusercontent.com/29984387/38460018-e968bb58-3a7f-11e8-8408-391d384bafa7.png)
![breadcrumbpouchopen](https://user-images.githubusercontent.com/29984387/38460019-e9747f56-3a7f-11e8-8608-d99197ec1038.png)

![photoshop_2018-04-07_16-23-53](https://user-images.githubusercontent.com/29984387/38460031-152680e0-3a80-11e8-9d87-f436f8abb53c.png)

**Comment by quat1024** [comment]
Sorry for keeping you waiting, busy with school :face_with_head_bandage: 

Thanks a million! these look great in game. I'm going to add one or two more things and post as v1.1

**Comment by quat1024** [comment]
Oh, I should ask, do either of you have curseforge profiles so I can add you as artists

**Comment by towerofnix** [comment]
@quat1024 I have a profile but I haven't touched in a hundred thousand years and it probably isn't connected to my own email. No worries; don't try adding me as an artist if you have to link a particular CF profile :P

**Comment by Spazmunki13** [comment]
No worries at all. :) I go by Spazmunki13 on Curseforge.

**Comment by quat1024** [comment]
Added to the project~

I pushed update 1.1 with the new art & some new features: https://minecraft.curseforge.com/projects/breadcrumb-trail/files/2553148
